// src/services/parcelEstimationService.ts

import { calculateLandscapingEstimate, type ParcelData, type EstimationResult } from './estimationEngine';
import { searchParcels, type ParcelMetadata } from './parcelSearchEngine';
import type { AddressIndex } from '../types/parcelTypes';

// Mock parcel datasets - in a real implementation, these would be loaded from JSON files
// generated by the parcel search engine
const MOCK_ADDRESS_INDEX: AddressIndex = {
  '123 main st, st. louis, mo 63101': 'stl_001',
  '456 oak ave, clayton, mo 63105': 'clayton_001',
  '789 pine rd, st. louis, mo 63103': 'stl_002',
  '321 elm st, kirkwood, mo 63122': 'kirkwood_001',
  '654 maple dr, university city, mo 63130': 'ucity_001'
};

const MOCK_PARCEL_METADATA: { [id: string]: ParcelMetadata } = {
  'stl_001': {
    id: 'stl_001',
    original_parcel_id: 'STL001',
    full_address: '123 Main St, St. Louis, MO 63101',
    latitude: 38.6495,
    longitude: -90.3005,
    property_type: 'residential',
    affluence_score: 35,
    area_sq_ft: 8500,
    bounding_box: {
      north: 38.6500,
      south: 38.6490,
      east: -90.3000,
      west: -90.3010
    }
  },
  'clayton_001': {
    id: 'clayton_001',
    original_parcel_id: 'CLAYTON001',
    full_address: '456 Oak Ave, Clayton, MO 63105',
    latitude: 38.6430,
    longitude: -90.3250,
    property_type: 'residential',
    affluence_score: 85,
    area_sq_ft: 12000,
    bounding_box: {
      north: 38.6440,
      south: 38.6420,
      east: -90.3240,
      west: -90.3260
    }
  },
  'stl_002': {
    id: 'stl_002',
    original_parcel_id: 'STL002',
    full_address: '789 Pine Rd, St. Louis, MO 63103',
    latitude: 38.6100,
    longitude: -90.2000,
    property_type: 'commercial',
    affluence_score: 45,
    area_sq_ft: 25000,
    bounding_box: {
      north: 38.6120,
      south: 38.6080,
      east: -90.1980,
      west: -90.2020
    }
  },
  'kirkwood_001': {
    id: 'kirkwood_001',
    original_parcel_id: 'KIRKWOOD001',
    full_address: '321 Elm St, Kirkwood, MO 63122',
    latitude: 38.5834,
    longitude: -90.4071,
    property_type: 'residential',
    affluence_score: 75,
    area_sq_ft: 10500
  },
  'ucity_001': {
    id: 'ucity_001',
    original_parcel_id: 'UCITY001',
    full_address: '654 Maple Dr, University City, MO 63130',
    latitude: 38.6570,
    longitude: -90.3090,
    property_type: 'residential',
    affluence_score: 80,
    area_sq_ft: 9200,
    bounding_box: {
      north: 38.6580,
      south: 38.6560,
      east: -90.3080,
      west: -90.3100
    }
  }
};

export interface ParcelLookupResult {
  success: boolean;
  parcel?: ParcelMetadata;
  error?: string;
}

export interface InstantEstimateResult {
  success: boolean;
  parcel?: ParcelMetadata;
  estimate?: EstimationResult;
  error?: string;
}

/**
 * Find parcel data for a given address
 */
export function findParcelByAddress(address: string): ParcelLookupResult {
  try {
    const results = searchParcels(address, MOCK_ADDRESS_INDEX, MOCK_PARCEL_METADATA);
    
    if (results.length === 0) {
      return {
        success: false,
        error: 'No parcel data found for this address. Please try a different address or use manual input.'
      };
    }
    
    // Return the first (best) match
    return {
      success: true,
      parcel: results[0]
    };
    
  } catch {
    return {
      success: false,
      error: 'Error searching for parcel data. Please try again.'
    };
  }
}

/**
 * Get instant landscaping estimate for an address
 */
export function getInstantEstimate(address: string): InstantEstimateResult {
  try {
    // First, find the parcel
    const parcelResult = findParcelByAddress(address);
    
    if (!parcelResult.success || !parcelResult.parcel) {
      return {
        success: false,
        error: parcelResult.error || 'Could not find parcel data for this address'
      };
    }
    
    const parcel = parcelResult.parcel;
    
    // Convert parcel metadata to estimation engine format
    const parcelData: ParcelData = {
      area: parcel.area_sq_ft,
      boundingBox: parcel.bounding_box,
      propertyType: parcel.property_type,
      affluenceScore: parcel.affluence_score
    };
    
    // Calculate estimate
    const estimate = calculateLandscapingEstimate(parcelData);
    
    if (!estimate.success) {
      return {
        success: false,
        parcel,
        error: estimate.error || 'Could not calculate estimate for this parcel'
      };
    }
    
    return {
      success: true,
      parcel,
      estimate
    };
    
  } catch {
    return {
      success: false,
      error: 'An unexpected error occurred while calculating the estimate'
    };
  }
}

/**
 * Get all available addresses for autocomplete/suggestions
 */
export function getAvailableAddresses(): string[] {
  return Object.values(MOCK_PARCEL_METADATA).map(parcel => parcel.full_address);
}

/**
 * Enhanced address suggestions that include parcel data
 */
export function getAddressSuggestionsWithParcelData(query: string): Array<{
  address: string;
  parcel: ParcelMetadata;
}> {
  const results = searchParcels(query, MOCK_ADDRESS_INDEX, MOCK_PARCEL_METADATA);
  
  return results.slice(0, 5).map(parcel => ({
    address: parcel.full_address,
    parcel
  }));
}